requires 'FindBin::libs';
requires 'DateTime';
requires 'DateTime::Format::ISO8601::Format';
requires 'Math::Trig';
requires 'File::Tempdir';
requires 'Mojolicious';
requires 'Template::Toolkit';
requires 'Moose';
requires 'namespace::autoclean';
